options:
  container-url:
    type: string
    default: "https://s3.amazonaws.com/cff-pairbox/cfpbj-0.1.tar.gz"
    description: "Url for container image"
  pub-keys:
    type: string
    default: ""
    description: pub keys for accessing running box
  ssh-port:
    type: int
    default: 22222
    description: "ssh port for launched container"
  name:
    type: string
    default: "devbox"
    description: "name for launched container"