- hosts: all
  vars:
    docker: /usr/local/bin/docker
  tasks:
    - name: Install required packages.
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - docker.io
      tags:
        - install
        - upgrade-charm

    - name: link docker binary
      command: ln -sf /usr/bin/docker.io creates={{docker}}
      tags:
        - install
        - upgrade-charm

    - name: pairbox upstart conf
      copy: src=files/pairbox_ssh.conf dest=/etc/init/pairbox_ssh.conf
      tags:
        - install
        - upgrade-charm

    - name: build container
      command: docker build --rm -t cfpbj ./ chdir={{charm_dir}}/docker
      tags:
        - install
        - upgrade-charm

    - name: Stop service
      command: docker stop devbox
      tags:
        - stop
        - config-changed

    - name: Start ssh
      command: docker run -d -P --name devbox cfpbj
      tags:
        - start
        - config-changed

    - name: start port forwarding
      service: name=pairbox_ssh state=started
      tags:
        - start

    - name: restart port forwarding
      service: name=pairbox_ssh state=restarted
      tags:
        - config-changed
